### ISSUE TITLE
[minidlna] How to make miniDLNA work remotely over ZeroTier?

### ISSUE THREAD

**Issue by vsisl** [vladgh/docker_base_images#107]
Hello!

First of all, thank you @vladgh for providing us with these images and keeping them up-to-date!

I'm running miniDLNA docker container (see compose file below) on Raspberry Pi 4. Furthermore, I use [ZeroTier](https://www.zerotier.com/) for remote access to the system. ZeroTier is installed directly on the OS, not in a container.

**miniDLNA works perfectly in my local network.** All devices (VLC on my laptop, smart TV, VLC on my phone) can see the DLNA service and stream from it.

But, **I can't make it work remotely over ZeroTier**. Using VLC, my **DLNA server just does not show up in the UPnP list**. However, I can access the web status page on port 8200. 

Any ideas how to make it work?

Thanks for help!

```yaml
version: "3.4"
services:
    minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    network_mode: "host"
    environment:
      - PGID=1000
      - PUID=1000
      - MINIDLNA_MEDIA_DIR_1=V,/media/video
      - MINIDLNA_MEDIA_DIR_2=A,/media/audio
      - MINIDLNA_FRIENDLY_NAME=RaspberryPi4-MiniDLNA
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hdd/nas-ntfs/Movies/:/media/video
      - /mnt/hdd/nas-ntfs/Music/:/media/audio
```
