### ISSUE TITLE
[minidlna] Please bump version to 1.3.0

### ISSUE THREAD

**Issue by n00ris** [vladgh/docker_base_images#108]
Hello,

current image ( December 13, 2020 at 06:25 PM , ID 0665ade0eb1b) still uses 

`minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1`

from 2017.
Please bump to 1.3.0 available since 2020-11-24  [1]

[1] https://sourceforge.net/projects/minidlna/files/

**Comment by accountForIssues** [comment]
@n00ris 
Here's my solution using docker-compose.

Directory structure:
```
minidlna/
|-- Dockerfile # edited from this repo
|-- data
|   |-- cache
|   |   |-- art_cache
|   |   `-- files.db
|   |-- minidlna.log
|   `-- minidlna.pid
|-- docker-compose.yml
`-- entrypoint.sh # from this repo
```

Dockerfile
```
FROM alpine

RUN apk --no-cache add bash curl tini shadow su-exec

# Add minidlna 1.3 latest
RUN apk --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/community/ add minidlna

COPY entrypoint.sh /

ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]

# Health check, changed localhost to 127.0.0.1 as 'localhost' was failing
HEALTHCHECK --interval=10s --timeout=10s --retries=6 CMD \
  curl --silent --fail 127.0.0.1:8200 || exit 1
```

docker-compose.yml
```
version: '3.3'
services:
    minidlna:
        build: .
        network_mode: host
        volumes:
            - '/home/user/mounted:/media:ro'
            # persistent volume so that the database survives system reboots and container restarts
            - './data:/minidlna'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - MINIDLNA_MEDIA_DIR=/media
            - MINIDLNA_FRIENDLY_NAME=Arch-Play
            - PUID=1000
            - PGID=1000
        container_name: minidlna
```
Then, just `docker-compose up -d` to start.

If you need to update in the future, you have to `docker-compose build`.
