### ISSUE TITLE
[minidlna] BrowseContentDirectory Returning UPnPError 402 - Invalid Args

### ISSUE THREAD

**Issue by jimbo27** [vladgh/docker_base_images#229]
I got the Docker image vladgh/minidlna up and running today. When I go into the DLNA library via the PC, I see all the videos, music and pictures. When I access the DLNA library via the TV, I see the music and videos. When I try to view the pictures I get an error.

Log:
```
=== Set user and group identifier
=== Set timezone
=== Set standard configuration
=== Set configuration from environment variables
=== Set permissions
=== Generate scan/rebuild flags
=== Start daemon
minidlna.c:1134: warn: Starting MiniDLNA version 1.3.1.
minidlna.c:394: warn: Creating new database at /minidlna/cache/files.db
minidlna.c:1182: warn: HTTP listening on port 8200
upnphttp.c:1074: warn: /favicon.ico not found, responding ERROR 404
playlist.c:135: warn: Parsing playlists...
playlist.c:269: warn: Finished parsing playlists.
monitor_inotify.c:223: warn: WARNING: Inotify max_user_watches [58883] is low or close to the number of used watches [1162] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.
upnpsoap.c:127: warn: BrowseContentDirectory Returning UPnPError 402: Invalid Args
upnpsoap.c:127: warn: BrowseContentDirectory Returning UPnPError 402: Invalid Args
upnpsoap.c:127: warn: BrowseContentDirectory Returning UPnPError 402: Invalid Args
```

Docker config:
```
version: '3.1'
services:
  minidlna:
    container_name: minidlna
    restart: unless-stopped
    network_mode: host
    image: vladgh/minidlna
    volumes:
      - /srv/dev-disk-by-uuid-67824a78-7d9f-4525-a407-eff360639079/music:/media/audio
      - /srv/dev-disk-by-uuid-67824a78-7d9f-4525-a407-eff360639079/video:/media/video
      - /srv/dev-disk-by-uuid-67824a78-7d9f-4525-a407-eff360639079/photo:/media/pictures
    environment:
      - MINIDLNA_FRIENDLY_NAME=MiniDLNA
      - TZ=Europe/Berlin
      - PUID=1004
      - PGID=100
      - MINIDLNA_MEDIA_DIR_1=A,/media/audio
      - MINIDLNA_MEDIA_DIR_2=V,/media/video
      - MINIDLNA_MEDIA_DIR_3=P,/media/pictures
```

![Clipboard 1](https://user-images.githubusercontent.com/5084469/229270988-30a36cbe-8730-4aa4-b8a7-e5cbb0709ad8.jpg)

Did I set something wrong? How can i fix this?
